export type AdminUser = {
	id: string;
	username: string;
	role: string;
	name: string;
	email: string;
	phone_code: string;
	phone_no: string;
	last_signin?: number;
	is_enabled: boolean;
	created: number;
	updated?: number;
	image?: string;
	as?: string;
};

export type Agent = {
	id: string;
	name: string;
	country?: string;
	region?: string;
	city?: string;
	address?: string;
	phone_code?: string;
	phone_no?: string;
	email?: string;
	website?: string;
	timezone?: number;
	is_verified: boolean;
	is_enable: boolean;
	created: number;
	updated?: number;
};

export type AgentUser = {
	id: string;
	agent_id: string;
	role: string;
	username: string;
	name: string;
	email?: string;
	phone_code?: string;
	phone_no?: string;
	is_enable: boolean;
	created: number;
	updated?: number;
	agent?: Agent;
	image?: string;
	as?: string;
};

export type User = {
	id: string;
	agent_id: string;
	username: string;
	user_type: string;
	name: string;
	gender?: string;
	birthdate?: string;
	citizenship?: string;
	identity_type?: string;
	identity_no?: string;
	country?: string;
	region?: string;
	city?: string;
	address?: string;
	email: string;
	phone_code: string;
	phone_no: string;
	occupation?: string;
	notes?: string;
	is_verified: boolean;
	email_verified: boolean;
	phone_verified: boolean;
	is_enable: boolean;
	created: number;
	updated?: number;
	agent?: Agent;
	image?: string;
	as?: string;
};

export type Disbursement = {
	id: string;
	agent_id: string;
	user_id?: string;
	from_currency: string;
	from_amount: number;
	from_type: string;
	from_name: string;
	from_gender?: string;
	from_birthdate?: string;
	from_citizenship: string;
	from_identity_type: string;
	from_identity_no: string;
	from_occupation?: string;
	from_country: string;
	from_region?: string;
	from_city?: string;
	from_address?: string;
	from_email?: string;
	from_phone_code?: string;
	from_phone_no?: string;
	from_notes?: string;
	to_contact: string;
	to_currency: string;
	to_amount: number;
	to_type: string;
	to_name: string;
	to_gender?: string;
	to_birthdate?: string;
	to_citizenship: string;
	to_identity_type: string;
	to_identity_no?: string;
	to_occupation?: string;
	to_country: string;
	to_region?: string;
	to_city?: string;
	to_address?: string;
	to_email?: string;
	to_phone_code?: string;
	to_phone_no?: string;
	to_notes?: string;
	to_relationship?: string;
	to_account: string;
	to_bank_name?: string;
	to_bank_account_no?: string;
	to_bank_account_name?: string;
	to_bank_country: string;
	to_bank_code?: string;
	to_bank_swift?: string;
	to_bank_address?: string;
	to_bank_email?: string;
	to_bank_phone_code?: string;
	to_bank_phone_no?: string;
	to_bank_website?: string;
	to_bank_notes?: string;
	rate_currency: string;
	rate: number;
	fee_currency: string;
	fee_amount_percent: number;
	fee_amount_fixed: number;
	fee_total: number;
	transfer_type: string;
	transfer_ref: string;
	transfer_on?: string;
	transfer_date?: string;
	fund_source?: string;
	purpose?: string;
	notes?: string;
	status: string;
	is_settled?: boolean;
	created: number;
	updated?: number;
	source_currency?: Currency;
	target_currency?: Currency;
	attachments?: DisbursementAttachment[];
};

export type UserType = User | AgentUser | AdminUser;

export type Rate = {
	source: string;
	from: string;
	to: string;
	rate_buy: number;
	rate_sell: number;
	spread_percentage: number;
	spread_fixed: number;
	auto: boolean;
	updated: number;
};

export type Currency = {
	id: string;
	name: string;
	symbol: string;
	type: string;
	is_active: boolean;
};

export type Contact = {
	id: string;
	agent_id: string;
	contact_type: string;
	name: string;
	gender?: string;
	birthdate?: string;
	citizenship?: string;
	identity_type?: string;
	identity_no?: string;
	country?: string;
	region?: string;
	city?: string;
	address?: string;
	email?: string;
	phone_code?: string;
	phone_no?: string;
	occupation?: string;
	notes?: string;
	is_verified: boolean;
	created: number;
	updated?: number;
	documents?: ContactDocument[];
	accounts?: ContactAccount[];
	relations?: ContactRelation[];
};

export type ContactDocument = {
	id: string;
	contact_id: string;
	document_type: string;
	document_data: string;
	notes?: string;
	is_verified: boolean;
	created: number;
	updated?: number;
};

export type ContactAccount = {
	id: string;
	contact_id: string;
	account_type: string;
	bank_id: string;
	bank_name: string;
	bank_code?: string;
	bank_swift?: string;
	owner_name: string;
	no: string;
	country?: string;
	address?: string;
	email?: string;
	website?: string;
	phone_code?: string;
	phone_no?: string;
	notes?: string;
	created: number;
	updated?: number;
};

export type ContactRelation = {
	contact_id: string;
	user_id: string;
	relation: string;
	updated: number;
};

export type DisbursementAttachment = {
	id: string;
	disbursement_id: string;
	attachment: string;
	submit_by: string;
	submit_owner: string;
	submit_time: number;
};
